version: '3'
services:
  php:
    container_name: personal-portal-php
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
    restart: always
  apache:
    container_name: personal-portal-apache
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
    restart: always
  mysql:
    container_name: personal-portal-mysql
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    restart: always
networks:
  frontend:
  backend:
